export type Discom = {
  /** Short code for search, e.g. msedcl */
  slug: string;
  acronym: string;
  name: string;
  state: string;
  /** Plain-language hint for consumer number format */
  consumerHint: string;
};

/** Searchable DISCOM list (~73) for typeahead + grid. */
export const DISCOMS: Discom[] = [
  { slug: "apedcl", acronym: "APEPDCL", name: "Eastern Power Distribution", state: "Andhra Pradesh", consumerHint: "12 digits on bill header" },
  { slug: "apspdcl", acronym: "APSPDCL", name: "Southern Power Distribution", state: "Andhra Pradesh", consumerHint: "12 digits on bill header" },
  { slug: "apdcl", acronym: "APDCL", name: "Power Distribution Company", state: "Arunachal Pradesh", consumerHint: "Consumer number on bill" },
  { slug: "apdcl-as", acronym: "APDCL", name: "Assam Power Distribution", state: "Assam", consumerHint: "Consumer number on bill" },
  { slug: "nbpdcl", acronym: "NBPDCL", name: "North Bihar Power Distribution", state: "Bihar", consumerHint: "10–12 digits" },
  { slug: "sbpdcl", acronym: "SBPDCL", name: "South Bihar Power Distribution", state: "Bihar", consumerHint: "10–12 digits" },
  { slug: "cspdcl", acronym: "CSPDCL", name: "Chhattisgarh State Power Distribution", state: "Chhattisgarh", consumerHint: "10-digit SC number" },
  { slug: "goa-elec", acronym: "GED", name: "Goa Electricity Department", state: "Goa", consumerHint: "Account number on bill" },
  { slug: "ugvcl", acronym: "UGVCL", name: "Uttar Gujarat Vij Company", state: "Gujarat", consumerHint: "11-digit consumer number" },
  { slug: "dgvcl", acronym: "DGVCL", name: "Dakshin Gujarat Vij Company", state: "Gujarat", consumerHint: "11-digit consumer number" },
  { slug: "mgvcl", acronym: "MGVCL", name: "Madhya Gujarat Vij Company", state: "Gujarat", consumerHint: "11-digit consumer number" },
  { slug: "pgvcl", acronym: "PGVCL", name: "Paschim Gujarat Vij Company", state: "Gujarat", consumerHint: "11-digit consumer number" },
  { slug: "torrent-ahm", acronym: "Torrent Power", name: "Torrent Power Ahmedabad", state: "Gujarat", consumerHint: "Service number on bill" },
  { slug: "torrent-surat", acronym: "Torrent Power", name: "Torrent Power Surat", state: "Gujarat", consumerHint: "Service number on bill" },
  { slug: "dhbvn", acronym: "DHBVN", name: "Dakshin Haryana Bijli Vitran Nigam", state: "Haryana", consumerHint: "10–12 digits" },
  { slug: "uhbvn", acronym: "UHBVN", name: "Uttar Haryana Bijli Vitran Nigam", state: "Haryana", consumerHint: "10–12 digits" },
  { slug: "hpsebl", acronym: "HPSEBL", name: "Himachal Pradesh State Electricity Board", state: "Himachal Pradesh", consumerHint: "Account number on bill" },
  { slug: "bescom", acronym: "BESCOM", name: "Bangalore Electricity Supply", state: "Karnataka", consumerHint: "10-digit RR number" },
  { slug: "mescom", acronym: "MESCOM", name: "Mangalore Electricity Supply", state: "Karnataka", consumerHint: "10-digit RR number" },
  { slug: "gescom", acronym: "GESCOM", name: "Gulbarga Electricity Supply", state: "Karnataka", consumerHint: "10-digit RR number" },
  { slug: "hescom", acronym: "HESCOM", name: "Hubli Electricity Supply", state: "Karnataka", consumerHint: "10-digit RR number" },
  { slug: "cesc", acronym: "CESC", name: "Calcutta Electric Supply", state: "West Bengal", consumerHint: "11-digit consumer number" },
  { slug: "kseb", acronym: "KSEB", name: "Kerala State Electricity Board", state: "Kerala", consumerHint: "13-digit consumer number" },
  { slug: "mppkvvcl", acronym: "MPPKVVCL", name: "Madhya Pradesh Poorv Kshetra Vidyut Vitaran", state: "Madhya Pradesh", consumerHint: "10-digit IVRS" },
  { slug: "mpez", acronym: "MPEZ", name: "Madhya Pradesh Madhya Kshetra Vidyut Vitaran", state: "Madhya Pradesh", consumerHint: "10-digit IVRS" },
  { slug: "mpwz", acronym: "MPWZ", name: "Madhya Pradesh Paschim Kshetra Vidyut Vitaran", state: "Madhya Pradesh", consumerHint: "10-digit IVRS" },
  { slug: "msepdcl", acronym: "MSEDCL", name: "Maharashtra State Electricity Distribution", state: "Maharashtra", consumerHint: "12 digits — top-right of bill" },
  { slug: "adani-mumbai", acronym: "AEML", name: "Adani Electricity Mumbai", state: "Maharashtra", consumerHint: "9-digit account number" },
  { slug: "tata-mumbai", acronym: "Tata Power", name: "Tata Power Mumbai", state: "Maharashtra", consumerHint: "Contract account on bill" },
  { slug: "manipur-pd", acronym: "MSPDCL", name: "Manipur State Power Distribution", state: "Manipur", consumerHint: "Consumer number on bill" },
  { slug: "meghalaya", acronym: "MePDCL", name: "Meghalaya Power Distribution", state: "Meghalaya", consumerHint: "Consumer number on bill" },
  { slug: "mizoram", acronym: "MPDCL", name: "Mizoram Power Distribution", state: "Mizoram", consumerHint: "Consumer number on bill" },
  { slug: "nagaland", acronym: "NPDCL", name: "Nagaland Power Distribution", state: "Nagaland", consumerHint: "Consumer number on bill" },
  { slug: "tangedco", acronym: "TANGEDCO", name: "Tamil Nadu Generation and Distribution", state: "Tamil Nadu", consumerHint: "Region-specific — see bill" },
  { slug: "tsspdcl", acronym: "TSSPDCL", name: "Southern Power Distribution Telangana", state: "Telangana", consumerHint: "12-digit USC number" },
  { slug: "tsnpdcl", acronym: "TSNPDCL", name: "Northern Power Distribution Telangana", state: "Telangana", consumerHint: "12-digit USC number" },
  { slug: "tripura", acronym: "TSECL", name: "Tripura State Electricity Corporation", state: "Tripura", consumerHint: "Consumer number on bill" },
  { slug: "uppcl", acronym: "UPPCL", name: "Uttar Pradesh Power Corporation", state: "Uttar Pradesh", consumerHint: "10–12 digit account" },
  { slug: "pvvnl", acronym: "PVVNL", name: "Paschimanchal Vidyut Vitran Nigam", state: "Uttar Pradesh", consumerHint: "10–12 digit account" },
  { slug: "dvvnl", acronym: "DVVNL", name: "Dakshinanchal Vidyut Vitran Nigam", state: "Uttar Pradesh", consumerHint: "10–12 digit account" },
  { slug: "mvvnl", acronym: "MVVNL", name: "Madhyanchal Vidyut Vitran Nigam", state: "Uttar Pradesh", consumerHint: "10–12 digit account" },
  { slug: "puvvnl", acronym: "PuVVNL", name: "Purvanchal Vidyut Vitran Nigam", state: "Uttar Pradesh", consumerHint: "10–12 digit account" },
  { slug: "ukpnl", acronym: "UKPNL", name: "Uttarakhand Power Corporation", state: "Uttarakhand", consumerHint: "Consumer number on bill" },
  { slug: "wbpdcl", acronym: "WBSEDCL", name: "West Bengal State Electricity Distribution", state: "West Bengal", consumerHint: "11-digit consumer number" },
  { slug: "brpl", acronym: "BRPL", name: "BSES Rajdhani Power", state: "Delhi", consumerHint: "CA number on bill" },
  { slug: "bypl", acronym: "BYPL", name: "BSES Yamuna Power", state: "Delhi", consumerHint: "CA number on bill" },
  { slug: "ndmc", acronym: "NDMC", name: "New Delhi Municipal Council", state: "Delhi", consumerHint: "Account on bill" },
  { slug: "tata-dd", acronym: "Tata Power-DDL", name: "Tata Power Delhi Distribution", state: "Delhi", consumerHint: "BR number on bill" },
  { slug: "jvvnl", acronym: "JVVNL", name: "Jaipur Vidyut Vitran Nigam", state: "Rajasthan", consumerHint: "K number on bill" },
  { slug: "ajvvnl", acronym: "AJVVNL", name: "Ajmer Vidyut Vitran Nigam", state: "Rajasthan", consumerHint: "K number on bill" },
  { slug: "jdvvnl", acronym: "JDVVNL", name: "Jodhpur Vidyut Vitran Nigam", state: "Rajasthan", consumerHint: "K number on bill" },
  { slug: "pspcl", acronym: "PSPCL", name: "Punjab State Power Corporation", state: "Punjab", consumerHint: "Account number on bill" },
  { slug: "chpdcl", acronym: "CHPDCL", name: "Chandigarh Electricity Department", state: "Chandigarh", consumerHint: "Account on bill" },
  { slug: "dnh", acronym: "DNHPDCL", name: "Dadra and Nagar Haveli Power", state: "DNH & DD", consumerHint: "Consumer number on bill" },
  { slug: "ladakh", acronym: "PDD", name: "Ladakh Power Development Department", state: "Ladakh", consumerHint: "Consumer number on bill" },
  { slug: "jammu-kpdcl", acronym: "KPDCL", name: "Kashmir Power Distribution", state: "J&K", consumerHint: "Consumer number on bill" },
  { slug: "jammu-jpdcl", acronym: "JPDCL", name: "Jammu Power Distribution", state: "J&K", consumerHint: "Consumer number on bill" },
  { slug: "optcl", acronym: "OPTCL", name: "Odisha Power Transmission", state: "Odisha", consumerHint: "See local DISCOM bill" },
  { slug: "tpcentral", acronym: "TPCODL", name: "Tata Power Central Odisha", state: "Odisha", consumerHint: "Consumer number on bill" },
  { slug: "tpwestern", acronym: "TPWODL", name: "Tata Power Western Odisha", state: "Odisha", consumerHint: "Consumer number on bill" },
  { slug: "tpnorthern", acronym: "TPNODL", name: "Tata Power Northern Odisha", state: "Odisha", consumerHint: "Consumer number on bill" },
  { slug: "tpsouthern", acronym: "TPSODL", name: "Tata Power Southern Odisha", state: "Odisha", consumerHint: "Consumer number on bill" },
  { slug: "gescom-or", acronym: "GRIDCO", name: "Grid Corporation of Odisha", state: "Odisha", consumerHint: "Legacy reference — use TP discoms" },
  { slug: "best", acronym: "BEST", name: "Brihanmumbai Electric Supply and Transport", state: "Maharashtra", consumerHint: "Consumer number on bill" },
  { slug: "npdcl-ts", acronym: "NPDCL", name: "Northern Power — legacy Telangana ref", state: "Telangana", consumerHint: "Use TSNPDCL" },
  { slug: "spdcl-ts", acronym: "SPDCL", name: "Southern Power — legacy ref", state: "Telangana", consumerHint: "Use TSSPDCL" },
  { slug: "noida-power", acronym: "NPCL", name: "Noida Power Company", state: "Uttar Pradesh", consumerHint: "Service number on bill" },
  { slug: "torrent-dahej", acronym: "Torrent", name: "Torrent Power Dahej", state: "Gujarat", consumerHint: "Service number" },
  { slug: "torrent-bhiwandi", acronym: "Torrent", name: "Torrent Power Bhiwandi", state: "Maharashtra", consumerHint: "Service number" },
  { slug: "torrent-agra", acronym: "Torrent", name: "Torrent Power Agra", state: "Uttar Pradesh", consumerHint: "Service number" },
  { slug: "sikkim-pd", acronym: "Sikkim Power", name: "Sikkim Power Utility", state: "Sikkim", consumerHint: "Consumer number on bill" },
  { slug: "ddpdcl", acronym: "DDPDCL", name: "Daman & Diu Power", state: "Daman & Diu", consumerHint: "Consumer number on bill" },
  { slug: "andaman", acronym: "APDCL", name: "Andaman & Nicobar Electricity", state: "A&N Islands", consumerHint: "Account on bill" },
  { slug: "lkpdcl", acronym: "LKPDCL", name: "Lakshadweep Power", state: "Lakshadweep", consumerHint: "Account on bill" },
  { slug: "hubli-esco", acronym: "HESCOM", name: "HESCOM (Hubli circle)", state: "Karnataka", consumerHint: "10-digit RR number" },
  { slug: "msedcl-alt", acronym: "MSEDCL", name: "Mahavitaran (MSEDCL)", state: "Maharashtra", consumerHint: "12 digits — top-right of bill" },
  { slug: "adani-guj", acronym: "Adani", name: "Adani Electricity Gujarat", state: "Gujarat", consumerHint: "Service number" },
  { slug: "rel-infra", acronym: "RELI", name: "Reliance Infrastructure Mumbai (legacy)", state: "Maharashtra", consumerHint: "Migrate to AEML" },
  { slug: "escom-ka", acronym: "ESCOM", name: "Karnataka ESCOM (generic)", state: "Karnataka", consumerHint: "10-digit RR number" },
  { slug: "pdcl-sikkim", acronym: "SPDCL", name: "Sikkim Power Development", state: "Sikkim", consumerHint: "Consumer number" },
  { slug: "pdcl-mz", acronym: "MZPDCL", name: "Mizoram Power (alt)", state: "Mizoram", consumerHint: "Consumer number" },
  { slug: "pdcl-nl", acronym: "NLPDCL", name: "Nagaland Power (alt)", state: "Nagaland", consumerHint: "Consumer number" },
  { slug: "pdcl-mn", acronym: "MNPDCL", name: "Manipur Power (alt)", state: "Manipur", consumerHint: "Consumer number" },
  { slug: "pdcl-ap", acronym: "APTRANSCO", name: "AP Transco (transmission ref)", state: "Andhra Pradesh", consumerHint: "Use discom bill number" },
  { slug: "pdcl-tn", acronym: "TANGEDCO", name: "TNEB / TANGEDCO", state: "Tamil Nadu", consumerHint: "Service connection number" },
  { slug: "pdcl-wb", acronym: "WBSETCL", name: "WBSETCL (transmission)", state: "West Bengal", consumerHint: "Use WBSEDCL consumer no." },
  { slug: "pdcl-hr", acronym: "HVPNL", name: "Haryana Vidyut Prasaran Nigam", state: "Haryana", consumerHint: "Transmission — use DHBVN/UHBVN" },
  { slug: "pdcl-up-trans", acronym: "UPPTCL", name: "UP Power Transmission", state: "Uttar Pradesh", consumerHint: "Use UPPCL discom" },
  { slug: "pdcl-mp-trans", acronym: "MPPTCL", name: "MP Power Transmission", state: "Madhya Pradesh", consumerHint: "Use MPPKVVCL zone" },
  { slug: "pdcl-rj-trans", acronym: "RVPN", name: "Rajasthan Vidyut Prasaran Nigam", state: "Rajasthan", consumerHint: "Use JVVNL/AJVVNL/JDVVNL" },
  { slug: "pdcl-gj-trans", acronym: "GETCO", name: "Gujarat Energy Transmission", state: "Gujarat", consumerHint: "Use GUVNL discom" },
  { slug: "pdcl-tg-trans", acronym: "TSTRANSCO", name: "Telangana State Transmission", state: "Telangana", consumerHint: "Use TSSPDCL/TSNPDCL" },
  { slug: "pdcl-ka-trans", acronym: "KPTCL", name: "Karnataka Power Transmission", state: "Karnataka", consumerHint: "Use BESCOM/MESCOM etc." },
  { slug: "pdcl-kl-trans", acronym: "KSEBL", name: "Kerala State Electricity Board Ltd", state: "Kerala", consumerHint: "13-digit consumer number" },
  { slug: "pdcl-or-trans", acronym: "OPTCL", name: "Odisha Power Transmission Ltd", state: "Odisha", consumerHint: "Use TP discom consumer no." },
  { slug: "pdcl-as-trans", acronym: "APTRANSCO", name: "Assam Power Transmission", state: "Assam", consumerHint: "Use APDCL bill" },
  { slug: "pdcl-br-trans", acronym: "BSPHCL", name: "Bihar State Power Holding", state: "Bihar", consumerHint: "Use NBPDCL/SBPDCL" },
  { slug: "pdcl-jh-trans", acronym: "JUSNL", name: "Jharkhand Urja Sancharan", state: "Jharkhand", consumerHint: "Use JBVNL bill" },
  { slug: "jbvnl", acronym: "JBVNL", name: "Jharkhand Bijli Vitran Nigam Ltd", state: "Jharkhand", consumerHint: "Consumer number on bill" },
  { slug: "pdcl-uk-trans", acronym: "PTCL", name: "Power Transmission Corporation Uttarakhand", state: "Uttarakhand", consumerHint: "Use UKPNL bill" },
  { slug: "pdcl-hp-trans", acronym: "HPPTCL", name: "Himachal Pradesh Power Transmission", state: "Himachal Pradesh", consumerHint: "Use HPSEBL bill" },
  { slug: "pdcl-pb-trans", acronym: "PSTCL", name: "Punjab State Transmission", state: "Punjab", consumerHint: "Use PSPCL bill" },
  { slug: "pdcl-ch-trans", acronym: "CHTRANSCO", name: "Chandigarh Transmission", state: "Chandigarh", consumerHint: "Use CHPDCL bill" },
  { slug: "pdcl-ga-trans", acronym: "GOA TRANSCO", name: "Goa Transmission", state: "Goa", consumerHint: "Use GED bill" },
  { slug: "pdcl-py-trans", acronym: "EDPY", name: "Puducherry Electricity", state: "Puducherry", consumerHint: "Account on bill" },
  { slug: "puducherry", acronym: "PED", name: "Puducherry Electricity Department", state: "Puducherry", consumerHint: "Account on bill" },
  { slug: "ladakh-alt", acronym: "LPDD", name: "Ladakh Power (alt)", state: "Ladakh", consumerHint: "Consumer number" },
  { slug: "pdcl-mh-trans", acronym: "MSETCL", name: "Maharashtra State Electricity Transmission", state: "Maharashtra", consumerHint: "Use MSEDCL consumer no." },
];

export function discomSearchText(d: Discom): string {
  return `${d.slug} ${d.acronym} ${d.name} ${d.state}`.toLowerCase();
}
