import type { Metadata } from "next";
import { Section } from "@/components/layout/Section";
import { createMetadata, siteConfig } from "@/lib/seo";

export const metadata: Metadata = createMetadata({
  title: "Terms of Service",
  description:
    "neuralkw terms of service. Terms governing use of our AI bill reconciliation platform for enterprise customers.",
  path: "/terms",
});

export default function TermsPage() {
  return (
    <main>
      <Section className="pt-28">
        <article className="prose prose-invert max-w-3xl">
          <h1 className="text-4xl font-bold text-white">Terms of Service</h1>
          <p className="mt-4 text-text-muted">Last updated: June 30, 2026</p>

          <div className="mt-8 space-y-6 text-text-muted">
            <section>
              <h2 className="text-xl font-semibold text-white">Agreement</h2>
              <p className="mt-2">
                By accessing or using neuralkw, you agree to these Terms of Service. If you are
                using the service on behalf of an organization, you represent that you have
                authority to bind that organization.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white">Service description</h2>
              <p className="mt-2">
                neuralkw provides AI-powered bill reconciliation, exception detection, and
                analytics for enterprise finance operations. The service matches vendor bills
                against user-provided agreement context.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white">Your responsibilities</h2>
              <ul className="mt-2 list-disc space-y-1 pl-6">
                <li>Provide accurate account and organization information</li>
                <li>Ensure you have rights to upload bills and agreements</li>
                <li>Review AI-generated reconciliation results before acting on them</li>
                <li>Maintain the security of your account credentials</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white">AI-generated outputs</h2>
              <p className="mt-2">
                Reconciliation results are generated by AI agents and provided as decision support.
                neuralkw does not provide financial, legal, or tax advice. You are responsible for
                final approval of payments and disputes.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white">Limitation of liability</h2>
              <p className="mt-2">
                The service is provided &quot;as is&quot; to the maximum extent permitted by law.
                neuralkw is not liable for indirect, incidental, or consequential damages arising
                from use of the platform.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white">Contact</h2>
              <p className="mt-2">
                Questions about these terms? Contact{" "}
                <a href={`mailto:${siteConfig.contactEmail}`} className="text-accent-cyan hover:underline">
                  {siteConfig.contactEmail}
                </a>.
              </p>
            </section>
          </div>
        </article>
      </Section>
    </main>
  );
}
